#include "Cpu6502Defines.h"

enum OpCodeAddressMode ADDRESS_MODE[] =
{
   OpCodeAddressMode::IMPLIED,            // 0x00
   OpCodeAddressMode::INDIRECT_INDEXED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::ABSOLUTE_ZERO_PAGE,
   OpCodeAddressMode::ABSOLUTE_ZERO_PAGE,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::IMMEDIATE,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::INVALID,

   OpCodeAddressMode::RELATIVE,           // 0x10
   OpCodeAddressMode::INDEXED_INDIRECT,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INDEXED_ZERO_PAGE,
   OpCodeAddressMode::INDEXED_ZERO_PAGE,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INVALID,

   OpCodeAddressMode::ABSOLUTE,           // 0x20
   OpCodeAddressMode::INDIRECT_INDEXED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::ABSOLUTE_ZERO_PAGE,
   OpCodeAddressMode::ABSOLUTE_ZERO_PAGE,
   OpCodeAddressMode::ABSOLUTE_ZERO_PAGE,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::IMMEDIATE,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::INVALID,

   OpCodeAddressMode::RELATIVE,           // 0x30
   OpCodeAddressMode::INDEXED_INDIRECT,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INDEXED_ZERO_PAGE,
   OpCodeAddressMode::INDEXED_ZERO_PAGE,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INVALID,

   OpCodeAddressMode::IMPLIED,           // 0x40
   OpCodeAddressMode::INDIRECT_INDEXED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::ABSOLUTE_ZERO_PAGE,
   OpCodeAddressMode::ABSOLUTE_ZERO_PAGE,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::IMMEDIATE,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::INVALID,

   OpCodeAddressMode::RELATIVE,           // 0x50
   OpCodeAddressMode::INDEXED_INDIRECT,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INDEXED_ZERO_PAGE,
   OpCodeAddressMode::INDEXED_ZERO_PAGE,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INVALID,

   OpCodeAddressMode::IMPLIED,           // 0x60
   OpCodeAddressMode::INDIRECT_INDEXED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::ABSOLUTE_ZERO_PAGE,
   OpCodeAddressMode::ABSOLUTE_ZERO_PAGE,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::IMMEDIATE,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INDIRECT,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::INVALID,

   OpCodeAddressMode::RELATIVE,           // 0x70
   OpCodeAddressMode::INDEXED_INDIRECT,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INDEXED_ZERO_PAGE,
   OpCodeAddressMode::INDEXED_ZERO_PAGE,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INVALID,

   OpCodeAddressMode::INVALID,            // 0x80
   OpCodeAddressMode::INDIRECT_INDEXED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::ABSOLUTE_ZERO_PAGE,
   OpCodeAddressMode::ABSOLUTE_ZERO_PAGE,
   OpCodeAddressMode::ABSOLUTE_ZERO_PAGE,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::INVALID,

   OpCodeAddressMode::RELATIVE,           // 0x90
   OpCodeAddressMode::INDEXED_INDIRECT,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INDEXED_ZERO_PAGE,
   OpCodeAddressMode::INDEXED_ZERO_PAGE,
   OpCodeAddressMode::INDEXED_ZERO_PAGE,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,

   OpCodeAddressMode::IMMEDIATE,           // 0xa0
   OpCodeAddressMode::INDIRECT_INDEXED,
   OpCodeAddressMode::IMMEDIATE,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::ABSOLUTE_ZERO_PAGE,
   OpCodeAddressMode::ABSOLUTE_ZERO_PAGE,
   OpCodeAddressMode::ABSOLUTE_ZERO_PAGE,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::IMMEDIATE,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::INVALID,

   OpCodeAddressMode::RELATIVE,           // 0xb0
   OpCodeAddressMode::INDEXED_INDIRECT,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INDEXED_ZERO_PAGE,
   OpCodeAddressMode::INDEXED_ZERO_PAGE,
   OpCodeAddressMode::INDEXED_ZERO_PAGE,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INVALID,

   OpCodeAddressMode::IMMEDIATE,           // 0xc0
   OpCodeAddressMode::INDIRECT_INDEXED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::ABSOLUTE_ZERO_PAGE,
   OpCodeAddressMode::ABSOLUTE_ZERO_PAGE,
   OpCodeAddressMode::ABSOLUTE_ZERO_PAGE,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::IMMEDIATE,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::INVALID,

   OpCodeAddressMode::RELATIVE,           // 0xd0
   OpCodeAddressMode::INDEXED_INDIRECT,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INDEXED_ZERO_PAGE,
   OpCodeAddressMode::INDEXED_ZERO_PAGE,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INVALID,

   OpCodeAddressMode::IMMEDIATE,           // 0xe0
   OpCodeAddressMode::INDIRECT_INDEXED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::ABSOLUTE_ZERO_PAGE,
   OpCodeAddressMode::ABSOLUTE_ZERO_PAGE,
   OpCodeAddressMode::ABSOLUTE_ZERO_PAGE,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::IMMEDIATE,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::ABSOLUTE,
   OpCodeAddressMode::INVALID,

   OpCodeAddressMode::RELATIVE,           // 0xf0
   OpCodeAddressMode::INDEXED_INDIRECT,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INDEXED_ZERO_PAGE,
   OpCodeAddressMode::INDEXED_ZERO_PAGE,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::IMPLIED,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INVALID,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INDEXED,
   OpCodeAddressMode::INVALID,

};


int OP_CODE_LENGTH[] =
{
   2, // IMMEDIATE
   3, // ABSOLUTE
   2, // ABSOLUTE_ZERO_PAGE
   1, // IMPLIED
   3, // INDEXED
   2, // INDEXED_ZERO_PAGE
   3, // INDIRECT
   2, // RELATIVE
   2, // INDIRECT_INDEXED
   2, // INDEXED_INDIRECT
   1  // INVALID
};


